apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.pv.name}}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.pv.capacity.storage}}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{.Values.pv.reclaimPolicy}}
  hostPath:
    path: {{.Values.pv.hostPath}}
