apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exercise3-pv-claim
spec:
  storageClassName: manual
  selector:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Mi
